[package]
name = "freqache"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license = "Apache-2.0"
description = "A thread-safe LFU cache which supports a custom eviction policy"
repository = "http://github.com/haydnv/freqache"
readme = "README.md"

categories = ["asynchronous", "caching", "concurrency", "data-structures"]
keywords = ["lfu", "cache", "custom", "eviction"]

[dependencies]
